osx_image: xcode10
language: objective-c
xcode_project: RxNimble.xcodeproj
xcode_scheme:
  - RxNimbleRxBlocking
  - RxNimbleRxTest

cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage

before_install:
  - carthageversion=$(carthage version)
  - if [ $carthageversion != "0.31.2" ]; then brew uninstall carthage; HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a85feeb75bc9e9beb7f2e9dc6e2ccc996a6aeaf5/Formula/carthage.rb; fi

jobs:
  include:
    - stage: prepare carthage cache
      script:
        - carthage bootstrap --no-use-binaries --cache-builds
    - stage: carthage builds
      script:
        - carthage build --cache-builds --no-skip-current --platform macOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform iOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform tvOS

stages:
  - prepare carthage cache
  - test
  - carthage builds
