osx_image: xcode9
language: objective-c
podfile: Demo/Podfile
cache: cocoapods
before_install:
  - gem install cocoapods -v '1.3.1'
  - pod repo update
script: cd Demo ; set -o pipefail && xcodebuild -workspace 'Demo.xcworkspace' -scheme 'Demo' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='11.0',name='iPhone 8' build test  | xcpretty -c --test
